# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/yeison/Documentos/python/dev/developing/Pinguino11/qtgui/gide/bloques/frame_plot/frame_plot.ui'
#
# Created: Sat Dec  7 18:36:31 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(493, 223)
        self.gridLayout_2 = QtGui.QGridLayout(Form)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtGui.QFrame(Form)
        self.frame_2.setMinimumSize(QtCore.QSize(10, 10))
        self.frame_2.setMaximumSize(QtCore.QSize(10, 10))
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_7 = QtGui.QFrame(Form)
        self.frame_7.setMinimumSize(QtCore.QSize(10, 0))
        self.frame_7.setMaximumSize(QtCore.QSize(10, 16777215))
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout.addWidget(self.frame_7)
        self.frame_4 = QtGui.QFrame(Form)
        self.frame_4.setMinimumSize(QtCore.QSize(10, 10))
        self.frame_4.setMaximumSize(QtCore.QSize(10, 10))
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout.addWidget(self.frame_4)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 2, 3, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtGui.QFrame(Form)
        self.frame.setMinimumSize(QtCore.QSize(10, 10))
        self.frame.setMaximumSize(QtCore.QSize(10, 10))
        self.frame.setObjectName("frame")
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_10 = QtGui.QFrame(Form)
        self.frame_10.setMinimumSize(QtCore.QSize(10, 0))
        self.frame_10.setMaximumSize(QtCore.QSize(10, 16777215))
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_2.addWidget(self.frame_10)
        self.frame_3 = QtGui.QFrame(Form)
        self.frame_3.setMinimumSize(QtCore.QSize(10, 10))
        self.frame_3.setMaximumSize(QtCore.QSize(10, 10))
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2.addWidget(self.frame_3)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 3, 1)
        self.frame_5 = QtGui.QFrame(Form)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_5.setObjectName("frame_5")
        self.gridLayout = QtGui.QGridLayout(self.frame_5)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_5, 0, 1, 1, 1)
        self.frame_6 = QtGui.QFrame(Form)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 10))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 10))
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_2.addWidget(self.frame_6, 2, 1, 1, 1)
        self.frame_15 = QtGui.QFrame(Form)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_15)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_15, 1, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))

