# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/yeison/.virtualenvs/pinguino_env/pinguino/pinguino-ide/qtgui/frames/hex_viewer_widget.ui'
#
# Created: Mon Jan 20 06:09:33 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_HexViewer(object):
    def setupUi(self, HexViewer):
        HexViewer.setObjectName("HexViewer")
        HexViewer.resize(722, 418)
        self.centralwidget = QtGui.QWidget(HexViewer)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_view = QtGui.QComboBox(self.centralwidget)
        self.comboBox_view.setMinimumSize(QtCore.QSize(141, 0))
        self.comboBox_view.setObjectName("comboBox_view")
        self.comboBox_view.addItem("")
        self.comboBox_view.addItem("")
        self.comboBox_view.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_view)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tableWidget_viewer = QtGui.QTableWidget(self.centralwidget)
        self.tableWidget_viewer.setAlternatingRowColors(True)
        self.tableWidget_viewer.setObjectName("tableWidget_viewer")
        self.tableWidget_viewer.setColumnCount(24)
        self.tableWidget_viewer.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_viewer.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_viewer.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_viewer.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_viewer.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_viewer.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_viewer.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_viewer.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_viewer.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_viewer.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_viewer.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_viewer.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_viewer.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_viewer.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_viewer.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_viewer.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_viewer.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_viewer.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_viewer.setHorizontalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_viewer.setHorizontalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_viewer.setHorizontalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_viewer.setHorizontalHeaderItem(19, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_viewer.setHorizontalHeaderItem(20, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_viewer.setHorizontalHeaderItem(21, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_viewer.setHorizontalHeaderItem(22, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_viewer.setHorizontalHeaderItem(23, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_viewer.setItem(0, 0, item)
        self.tableWidget_viewer.horizontalHeader().setDefaultSectionSize(37)
        self.gridLayout.addWidget(self.tableWidget_viewer, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_close = QtGui.QPushButton(self.centralwidget)
        self.pushButton_close.setMinimumSize(QtCore.QSize(101, 0))
        self.pushButton_close.setMaximumSize(QtCore.QSize(101, 16777215))
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout_2.addWidget(self.pushButton_close)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_save_changes = QtGui.QPushButton(self.centralwidget)
        self.pushButton_save_changes.setEnabled(False)
        self.pushButton_save_changes.setMinimumSize(QtCore.QSize(211, 0))
        self.pushButton_save_changes.setMaximumSize(QtCore.QSize(281, 16777215))
        self.pushButton_save_changes.setObjectName("pushButton_save_changes")
        self.horizontalLayout_2.addWidget(self.pushButton_save_changes)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        HexViewer.setCentralWidget(self.centralwidget)

        self.retranslateUi(HexViewer)
        QtCore.QMetaObject.connectSlotsByName(HexViewer)

    def retranslateUi(self, HexViewer):
        HexViewer.setWindowTitle(QtGui.QApplication.translate("HexViewer", "Hex Viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_view.setItemText(0, QtGui.QApplication.translate("HexViewer", "HEX (FF)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_view.setItemText(1, QtGui.QApplication.translate("HexViewer", "HEX (0xFF)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_view.setItemText(2, QtGui.QApplication.translate("HexViewer", "DEC", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_viewer.verticalHeaderItem(0).setText(QtGui.QApplication.translate("HexViewer", "000000", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_viewer.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("HexViewer", "00", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_viewer.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("HexViewer", "01", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_viewer.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("HexViewer", "02", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_viewer.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("HexViewer", "03", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_viewer.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("HexViewer", "04", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_viewer.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("HexViewer", "05", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_viewer.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("HexViewer", "06", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_viewer.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("HexViewer", "07", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_viewer.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("HexViewer", "08", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_viewer.horizontalHeaderItem(9).setText(QtGui.QApplication.translate("HexViewer", "09", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_viewer.horizontalHeaderItem(10).setText(QtGui.QApplication.translate("HexViewer", "0A", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_viewer.horizontalHeaderItem(11).setText(QtGui.QApplication.translate("HexViewer", "0B", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_viewer.horizontalHeaderItem(12).setText(QtGui.QApplication.translate("HexViewer", "0C", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_viewer.horizontalHeaderItem(13).setText(QtGui.QApplication.translate("HexViewer", "0D", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_viewer.horizontalHeaderItem(14).setText(QtGui.QApplication.translate("HexViewer", "0E", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_viewer.horizontalHeaderItem(15).setText(QtGui.QApplication.translate("HexViewer", "0F", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_viewer.horizontalHeaderItem(16).setText(QtGui.QApplication.translate("HexViewer", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_viewer.horizontalHeaderItem(17).setText(QtGui.QApplication.translate("HexViewer", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_viewer.horizontalHeaderItem(18).setText(QtGui.QApplication.translate("HexViewer", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_viewer.horizontalHeaderItem(19).setText(QtGui.QApplication.translate("HexViewer", "13", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_viewer.horizontalHeaderItem(20).setText(QtGui.QApplication.translate("HexViewer", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_viewer.horizontalHeaderItem(21).setText(QtGui.QApplication.translate("HexViewer", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_viewer.horizontalHeaderItem(22).setText(QtGui.QApplication.translate("HexViewer", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_viewer.horizontalHeaderItem(23).setText(QtGui.QApplication.translate("HexViewer", "17", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget_viewer.isSortingEnabled()
        self.tableWidget_viewer.setSortingEnabled(False)
        self.tableWidget_viewer.item(0, 0).setText(QtGui.QApplication.translate("HexViewer", "FF", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_viewer.setSortingEnabled(__sortingEnabled)
        self.pushButton_close.setText(QtGui.QApplication.translate("HexViewer", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_save_changes.setText(QtGui.QApplication.translate("HexViewer", "Save changes as...", None, QtGui.QApplication.UnicodeUTF8))

