# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/yeison/Documentos/Pinguino/pinguino-ide/qtgui/frames/main.ui'
#
# Created: Thu Dec 12 20:11:09 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_PinguinoIDE(object):
    def setupUi(self, PinguinoIDE):
        PinguinoIDE.setObjectName("PinguinoIDE")
        PinguinoIDE.resize(966, 633)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/art/windowIcon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PinguinoIDE.setWindowIcon(icon)
        PinguinoIDE.setDockOptions(QtGui.QMainWindow.AllowNestedDocks|QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks|QtGui.QMainWindow.ForceTabbedDocks)
        PinguinoIDE.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtGui.QWidget(PinguinoIDE)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_15 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setSpacing(0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.tabWidget_files = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_files.setDocumentMode(True)
        self.tabWidget_files.setTabsClosable(True)
        self.tabWidget_files.setMovable(True)
        self.tabWidget_files.setObjectName("tabWidget_files")
        self.gridLayout_15.addWidget(self.tabWidget_files, 0, 0, 1, 1)
        self.frame_logo = QtGui.QFrame(self.centralwidget)
        self.frame_logo.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_logo.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_logo.setObjectName("frame_logo")
        self.gridLayout = QtGui.QGridLayout(self.frame_logo)
        self.gridLayout.setObjectName("gridLayout")
        self.label_logo = QtGui.QLabel(self.frame_logo)
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap(":/logo/art/banner.png"))
        self.label_logo.setObjectName("label_logo")
        self.gridLayout.addWidget(self.label_logo, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout_15.addWidget(self.frame_logo, 1, 0, 1, 1)
        self.tabWidget_graphical = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_graphical.setDocumentMode(True)
        self.tabWidget_graphical.setTabsClosable(True)
        self.tabWidget_graphical.setMovable(True)
        self.tabWidget_graphical.setObjectName("tabWidget_graphical")
        self.gridLayout_15.addWidget(self.tabWidget_graphical, 2, 0, 1, 1)
        PinguinoIDE.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(PinguinoIDE)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 966, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuPinguino = QtGui.QMenu(self.menubar)
        self.menuPinguino.setObjectName("menuPinguino")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuLinks = QtGui.QMenu(self.menuHelp)
        self.menuLinks.setObjectName("menuLinks")
        self.menuSource = QtGui.QMenu(self.menubar)
        self.menuSource.setObjectName("menuSource")
        PinguinoIDE.setMenuBar(self.menubar)
        self.dockWidget_tools = QtGui.QDockWidget(PinguinoIDE)
        self.dockWidget_tools.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget_tools.setObjectName("dockWidget_tools")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_4 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget_tools = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidget_tools.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget_tools.setObjectName("tabWidget_tools")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setHorizontalSpacing(0)
        self.gridLayout_9.setVerticalSpacing(4)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.comboBox_files = QtGui.QComboBox(self.tab_5)
        self.comboBox_files.setObjectName("comboBox_files")
        self.comboBox_files.addItem("")
        self.comboBox_files.addItem("")
        self.comboBox_files.addItem("")
        self.comboBox_files.addItem("")
        self.gridLayout_9.addWidget(self.comboBox_files, 0, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_path = QtGui.QLabel(self.tab_5)
        self.label_path.setMargin(0)
        self.label_path.setIndent(27)
        self.label_path.setObjectName("label_path")
        self.verticalLayout.addWidget(self.label_path)
        self.listWidget_files = QtGui.QListWidget(self.tab_5)
        self.listWidget_files.setIconSize(QtCore.QSize(25, 25))
        self.listWidget_files.setObjectName("listWidget_files")
        self.verticalLayout.addWidget(self.listWidget_files)
        self.gridLayout_9.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.tabWidget_tools.addTab(self.tab_5, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tabWidget_browser = QtGui.QTabWidget(self.tab_3)
        self.tabWidget_browser.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget_browser.setObjectName("tabWidget_browser")
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_7)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tableWidget_variables = QtGui.QTableWidget(self.tab_7)
        self.tableWidget_variables.setFrameShape(QtGui.QFrame.NoFrame)
        self.tableWidget_variables.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_variables.setAlternatingRowColors(True)
        self.tableWidget_variables.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tableWidget_variables.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_variables.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidget_variables.setObjectName("tableWidget_variables")
        self.tableWidget_variables.setColumnCount(2)
        self.tableWidget_variables.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_variables.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_variables.setHorizontalHeaderItem(1, item)
        self.tableWidget_variables.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_6.addWidget(self.tableWidget_variables, 0, 0, 1, 1)
        self.tabWidget_browser.addTab(self.tab_7, "")
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tableWidget_functions = QtGui.QTableWidget(self.tab_6)
        self.tableWidget_functions.setFrameShape(QtGui.QFrame.NoFrame)
        self.tableWidget_functions.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_functions.setAlternatingRowColors(True)
        self.tableWidget_functions.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tableWidget_functions.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_functions.setShowGrid(True)
        self.tableWidget_functions.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidget_functions.setObjectName("tableWidget_functions")
        self.tableWidget_functions.setColumnCount(3)
        self.tableWidget_functions.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_functions.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_functions.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_functions.setHorizontalHeaderItem(2, item)
        self.tableWidget_functions.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_5.addWidget(self.tableWidget_functions, 0, 0, 1, 1)
        self.tabWidget_browser.addTab(self.tab_6, "")
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_8)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tableWidget_directives = QtGui.QTableWidget(self.tab_8)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.tableWidget_directives.setPalette(palette)
        self.tableWidget_directives.setFrameShape(QtGui.QFrame.NoFrame)
        self.tableWidget_directives.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_directives.setAlternatingRowColors(True)
        self.tableWidget_directives.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tableWidget_directives.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_directives.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidget_directives.setObjectName("tableWidget_directives")
        self.tableWidget_directives.setColumnCount(3)
        self.tableWidget_directives.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_directives.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_directives.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_directives.setHorizontalHeaderItem(2, item)
        self.tableWidget_directives.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_7.addWidget(self.tableWidget_directives, 0, 0, 1, 1)
        self.tabWidget_browser.addTab(self.tab_8, "")
        self.gridLayout_8.addWidget(self.tabWidget_browser, 0, 0, 1, 1)
        self.tabWidget_tools.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_12 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_12.setSpacing(0)
        self.gridLayout_12.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.groupBox = QtGui.QGroupBox(self.tab_4)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setContentsMargins(0, -1, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.lineEdit_replace = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_replace.setObjectName("lineEdit_replace")
        self.gridLayout_11.addWidget(self.lineEdit_replace, 0, 0, 1, 2)
        self.pushButton_replace = QtGui.QPushButton(self.groupBox)
        self.pushButton_replace.setObjectName("pushButton_replace")
        self.gridLayout_11.addWidget(self.pushButton_replace, 1, 0, 1, 1)
        self.pushButton_replace_all = QtGui.QPushButton(self.groupBox)
        self.pushButton_replace_all.setObjectName("pushButton_replace_all")
        self.gridLayout_11.addWidget(self.pushButton_replace_all, 1, 1, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox, 1, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem2, 2, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setContentsMargins(0, -1, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.lineEdit_search = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_search.setText("")
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.gridLayout_10.addWidget(self.lineEdit_search, 0, 0, 1, 2)
        self.pushButton_search_previous = QtGui.QPushButton(self.groupBox_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/icon_up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_search_previous.setIcon(icon1)
        self.pushButton_search_previous.setObjectName("pushButton_search_previous")
        self.gridLayout_10.addWidget(self.pushButton_search_previous, 1, 0, 1, 1)
        self.pushButton_search_next = QtGui.QPushButton(self.groupBox_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/icon_down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_search_next.setIcon(icon2)
        self.pushButton_search_next.setObjectName("pushButton_search_next")
        self.gridLayout_10.addWidget(self.pushButton_search_next, 1, 1, 1, 1)
        self.checkBox_case_sensitive = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_case_sensitive.setObjectName("checkBox_case_sensitive")
        self.gridLayout_10.addWidget(self.checkBox_case_sensitive, 2, 0, 1, 2)
        self.gridLayout_12.addWidget(self.groupBox_2, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem3, 4, 0, 1, 1)
        self.label_replace_info = QtGui.QLabel(self.tab_4)
        self.label_replace_info.setText("")
        self.label_replace_info.setObjectName("label_replace_info")
        self.gridLayout_12.addWidget(self.label_replace_info, 3, 0, 1, 1)
        self.tabWidget_tools.addTab(self.tab_4, "")
        self.gridLayout_4.addWidget(self.tabWidget_tools, 0, 0, 1, 1)
        self.dockWidget_tools.setWidget(self.dockWidgetContents)
        PinguinoIDE.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_tools)
        self.dockWidget_output = QtGui.QDockWidget(PinguinoIDE)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dockWidget_output.setFont(font)
        self.dockWidget_output.setFeatures(QtGui.QDockWidget.DockWidgetFeatureMask)
        self.dockWidget_output.setObjectName("dockWidget_output")
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.plainTextEdit_output = QtGui.QPlainTextEdit(self.dockWidgetContents_2)
        self.plainTextEdit_output.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Ubuntu Mono\";")
        self.plainTextEdit_output.setFrameShape(QtGui.QFrame.NoFrame)
        self.plainTextEdit_output.setReadOnly(True)
        self.plainTextEdit_output.setObjectName("plainTextEdit_output")
        self.gridLayout_3.addWidget(self.plainTextEdit_output, 0, 0, 1, 1)
        self.dockWidget_output.setWidget(self.dockWidgetContents_2)
        PinguinoIDE.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_output)
        self.toolBar_files = QtGui.QToolBar(PinguinoIDE)
        self.toolBar_files.setMovable(False)
        self.toolBar_files.setIconSize(QtCore.QSize(32, 32))
        self.toolBar_files.setObjectName("toolBar_files")
        PinguinoIDE.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_files)
        self.toolBar_undo_redo = QtGui.QToolBar(PinguinoIDE)
        self.toolBar_undo_redo.setMovable(False)
        self.toolBar_undo_redo.setIconSize(QtCore.QSize(32, 32))
        self.toolBar_undo_redo.setObjectName("toolBar_undo_redo")
        PinguinoIDE.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_undo_redo)
        self.toolBar_edit = QtGui.QToolBar(PinguinoIDE)
        self.toolBar_edit.setMovable(False)
        self.toolBar_edit.setIconSize(QtCore.QSize(32, 32))
        self.toolBar_edit.setObjectName("toolBar_edit")
        PinguinoIDE.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_edit)
        self.toolBar_search_replace = QtGui.QToolBar(PinguinoIDE)
        self.toolBar_search_replace.setMovable(False)
        self.toolBar_search_replace.setIconSize(QtCore.QSize(32, 32))
        self.toolBar_search_replace.setObjectName("toolBar_search_replace")
        PinguinoIDE.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_search_replace)
        self.toolBar_pinguino = QtGui.QToolBar(PinguinoIDE)
        self.toolBar_pinguino.setMovable(False)
        self.toolBar_pinguino.setIconSize(QtCore.QSize(32, 32))
        self.toolBar_pinguino.setObjectName("toolBar_pinguino")
        PinguinoIDE.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_pinguino)
        self.toolBar_board = QtGui.QToolBar(PinguinoIDE)
        self.toolBar_board.setEnabled(True)
        self.toolBar_board.setMaximumSize(QtCore.QSize(16777215, 22))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.toolBar_board.setPalette(palette)
        self.toolBar_board.setMovable(False)
        self.toolBar_board.setAllowedAreas(QtCore.Qt.BottomToolBarArea|QtCore.Qt.TopToolBarArea)
        self.toolBar_board.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolBar_board.setFloatable(False)
        self.toolBar_board.setObjectName("toolBar_board")
        PinguinoIDE.addToolBar(QtCore.Qt.BottomToolBarArea, self.toolBar_board)
        self.dockWidget_blocks = QtGui.QDockWidget(PinguinoIDE)
        self.dockWidget_blocks.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget_blocks.setObjectName("dockWidget_blocks")
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.gridLayout_13 = QtGui.QGridLayout(self.dockWidgetContents_4)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setSpacing(0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.tabWidget_blocks_tools = QtGui.QTabWidget(self.dockWidgetContents_4)
        self.tabWidget_blocks_tools.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget_blocks_tools.setObjectName("tabWidget_blocks_tools")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget_blocks = QtGui.QTabWidget(self.tab)
        self.tabWidget_blocks.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget_blocks.setObjectName("tabWidget_blocks")
        self.gridLayout_2.addWidget(self.tabWidget_blocks, 0, 0, 1, 1)
        self.tabWidget_blocks_tools.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_14 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setHorizontalSpacing(0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_pathg = QtGui.QLabel(self.tab_2)
        self.label_pathg.setMargin(0)
        self.label_pathg.setIndent(27)
        self.label_pathg.setObjectName("label_pathg")
        self.verticalLayout_2.addWidget(self.label_pathg)
        self.listWidget_filesg = QtGui.QListWidget(self.tab_2)
        self.listWidget_filesg.setIconSize(QtCore.QSize(25, 25))
        self.listWidget_filesg.setObjectName("listWidget_filesg")
        self.verticalLayout_2.addWidget(self.listWidget_filesg)
        self.gridLayout_14.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.comboBox_filesg = QtGui.QComboBox(self.tab_2)
        self.comboBox_filesg.setObjectName("comboBox_filesg")
        self.comboBox_filesg.addItem("")
        self.comboBox_filesg.addItem("")
        self.comboBox_filesg.addItem("")
        self.comboBox_filesg.addItem("")
        self.gridLayout_14.addWidget(self.comboBox_filesg, 0, 0, 1, 1)
        self.tabWidget_blocks_tools.addTab(self.tab_2, "")
        self.gridLayout_13.addWidget(self.tabWidget_blocks_tools, 0, 0, 1, 1)
        self.dockWidget_blocks.setWidget(self.dockWidgetContents_4)
        PinguinoIDE.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_blocks)
        self.toolBar_graphical = QtGui.QToolBar(PinguinoIDE)
        self.toolBar_graphical.setMovable(False)
        self.toolBar_graphical.setIconSize(QtCore.QSize(32, 32))
        self.toolBar_graphical.setObjectName("toolBar_graphical")
        PinguinoIDE.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_graphical)
        self.toolBar_switch = QtGui.QToolBar(PinguinoIDE)
        self.toolBar_switch.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.toolBar_switch.setMovable(False)
        self.toolBar_switch.setIconSize(QtCore.QSize(32, 32))
        self.toolBar_switch.setObjectName("toolBar_switch")
        PinguinoIDE.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_switch)
        self.actionNew_file = QtGui.QAction(PinguinoIDE)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/toolbar/toolbar/new_file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew_file.setIcon(icon3)
        self.actionNew_file.setObjectName("actionNew_file")
        self.actionOpen_file = QtGui.QAction(PinguinoIDE)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/toolbar/toolbar/open_file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_file.setIcon(icon4)
        self.actionOpen_file.setObjectName("actionOpen_file")
        self.actionSave_file = QtGui.QAction(PinguinoIDE)
        self.actionSave_file.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/toolbar/toolbar/save_file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_file.setIcon(icon5)
        self.actionSave_file.setObjectName("actionSave_file")
        self.actionClose_file = QtGui.QAction(PinguinoIDE)
        self.actionClose_file.setEnabled(False)
        self.actionClose_file.setObjectName("actionClose_file")
        self.actionUndo = QtGui.QAction(PinguinoIDE)
        self.actionUndo.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/toolbar/toolbar/undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon6)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtGui.QAction(PinguinoIDE)
        self.actionRedo.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/toolbar/toolbar/redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon7)
        self.actionRedo.setObjectName("actionRedo")
        self.actionCut = QtGui.QAction(PinguinoIDE)
        self.actionCut.setEnabled(False)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/toolbar/toolbar/cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut.setIcon(icon8)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtGui.QAction(PinguinoIDE)
        self.actionCopy.setEnabled(False)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/toolbar/toolbar/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon9)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtGui.QAction(PinguinoIDE)
        self.actionPaste.setEnabled(False)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/toolbar/toolbar/paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon10)
        self.actionPaste.setObjectName("actionPaste")
        self.actionClear = QtGui.QAction(PinguinoIDE)
        self.actionClear.setObjectName("actionClear")
        self.actionSelect = QtGui.QAction(PinguinoIDE)
        self.actionSelect.setObjectName("actionSelect")
        self.actionSearch = QtGui.QAction(PinguinoIDE)
        self.actionSearch.setEnabled(False)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/toolbar/toolbar/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSearch.setIcon(icon11)
        self.actionSearch.setObjectName("actionSearch")
        self.actionSearch_and_replace = QtGui.QAction(PinguinoIDE)
        self.actionSearch_and_replace.setEnabled(False)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/toolbar/toolbar/replace.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSearch_and_replace.setIcon(icon12)
        self.actionSearch_and_replace.setObjectName("actionSearch_and_replace")
        self.actionSelect_board = QtGui.QAction(PinguinoIDE)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/toolbar/toolbar/board.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSelect_board.setIcon(icon13)
        self.actionSelect_board.setObjectName("actionSelect_board")
        self.actionCompile = QtGui.QAction(PinguinoIDE)
        self.actionCompile.setEnabled(False)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/toolbar/toolbar/compile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCompile.setIcon(icon14)
        self.actionCompile.setObjectName("actionCompile")
        self.actionUpload = QtGui.QAction(PinguinoIDE)
        self.actionUpload.setEnabled(False)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/toolbar/toolbar/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUpload.setIcon(icon15)
        self.actionUpload.setObjectName("actionUpload")
        self.actionSettings = QtGui.QAction(PinguinoIDE)
        self.actionSettings.setObjectName("actionSettings")
        self.actionQuit = QtGui.QAction(PinguinoIDE)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtGui.QAction(PinguinoIDE)
        self.actionAbout.setObjectName("actionAbout")
        self.actionComment_Uncomment_region = QtGui.QAction(PinguinoIDE)
        self.actionComment_Uncomment_region.setObjectName("actionComment_Uncomment_region")
        self.actionComment_out_region = QtGui.QAction(PinguinoIDE)
        self.actionComment_out_region.setObjectName("actionComment_out_region")
        self.actionBoard_info = QtGui.QAction(PinguinoIDE)
        self.actionBoard_info.setEnabled(False)
        self.actionBoard_info.setAutoRepeat(False)
        self.actionBoard_info.setVisible(True)
        self.actionBoard_info.setObjectName("actionBoard_info")
        self.actionStdout = QtGui.QAction(PinguinoIDE)
        self.actionStdout.setObjectName("actionStdout")
        self.actionSwitch_ide = QtGui.QAction(PinguinoIDE)
        self.actionSwitch_ide.setCheckable(True)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/toolbar/toolbar/switch_to_graphical.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon16.addPixmap(QtGui.QPixmap(":/toolbar/toolbar/switch_to_text.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSwitch_ide.setIcon(icon16)
        self.actionSwitch_ide.setObjectName("actionSwitch_ide")
        self.actionSave_image = QtGui.QAction(PinguinoIDE)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/toolbar/toolbar/save_image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_image.setIcon(icon17)
        self.actionSave_image.setObjectName("actionSave_image")
        self.actionView_Pinguino_code = QtGui.QAction(PinguinoIDE)
        self.actionView_Pinguino_code.setEnabled(False)
        self.actionView_Pinguino_code.setObjectName("actionView_Pinguino_code")
        self.actionSave_all = QtGui.QAction(PinguinoIDE)
        self.actionSave_all.setObjectName("actionSave_all")
        self.actionClose_all = QtGui.QAction(PinguinoIDE)
        self.actionClose_all.setObjectName("actionClose_all")
        self.actionWebsite = QtGui.QAction(PinguinoIDE)
        self.actionWebsite.setObjectName("actionWebsite")
        self.actionWiki = QtGui.QAction(PinguinoIDE)
        self.actionWiki.setObjectName("actionWiki")
        self.actionForum = QtGui.QAction(PinguinoIDE)
        self.actionForum.setObjectName("actionForum")
        self.actionBlog = QtGui.QAction(PinguinoIDE)
        self.actionBlog.setObjectName("actionBlog")
        self.actionGroup = QtGui.QAction(PinguinoIDE)
        self.actionGroup.setObjectName("actionGroup")
        self.actionShop = QtGui.QAction(PinguinoIDE)
        self.actionShop.setObjectName("actionShop")
        self.actionGitHub = QtGui.QAction(PinguinoIDE)
        self.actionGitHub.setObjectName("actionGitHub")
        self.actionSave_as = QtGui.QAction(PinguinoIDE)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionCurrent_Board = QtGui.QAction(PinguinoIDE)
        self.actionCurrent_Board.setObjectName("actionCurrent_Board")
        self.menuFile.addAction(self.actionNew_file)
        self.menuFile.addAction(self.actionOpen_file)
        self.menuFile.addAction(self.actionSave_file)
        self.menuFile.addAction(self.actionClose_file)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionSave_all)
        self.menuFile.addAction(self.actionClose_all)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionSearch)
        self.menuEdit.addAction(self.actionSearch_and_replace)
        self.menuEdit.addSeparator()
        self.menuView.addAction(self.actionView_Pinguino_code)
        self.menuView.addAction(self.actionStdout)
        self.menuView.addAction(self.actionCurrent_Board)
        self.menuPinguino.addAction(self.actionSelect_board)
        self.menuPinguino.addAction(self.actionCompile)
        self.menuPinguino.addAction(self.actionUpload)
        self.menuLinks.addAction(self.actionGitHub)
        self.menuLinks.addAction(self.actionWebsite)
        self.menuLinks.addAction(self.actionWiki)
        self.menuLinks.addAction(self.actionForum)
        self.menuLinks.addAction(self.actionBlog)
        self.menuLinks.addAction(self.actionGroup)
        self.menuLinks.addAction(self.actionShop)
        self.menuHelp.addAction(self.menuLinks.menuAction())
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuSource.addAction(self.actionComment_out_region)
        self.menuSource.addAction(self.actionComment_Uncomment_region)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuSource.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuPinguino.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar_files.addAction(self.actionNew_file)
        self.toolBar_files.addAction(self.actionOpen_file)
        self.toolBar_files.addAction(self.actionSave_file)
        self.toolBar_files.addSeparator()
        self.toolBar_undo_redo.addAction(self.actionUndo)
        self.toolBar_undo_redo.addAction(self.actionRedo)
        self.toolBar_undo_redo.addSeparator()
        self.toolBar_edit.addAction(self.actionCut)
        self.toolBar_edit.addAction(self.actionCopy)
        self.toolBar_edit.addAction(self.actionPaste)
        self.toolBar_edit.addSeparator()
        self.toolBar_search_replace.addAction(self.actionSearch)
        self.toolBar_search_replace.addAction(self.actionSearch_and_replace)
        self.toolBar_search_replace.addSeparator()
        self.toolBar_pinguino.addAction(self.actionSelect_board)
        self.toolBar_pinguino.addAction(self.actionCompile)
        self.toolBar_pinguino.addAction(self.actionUpload)
        self.toolBar_pinguino.addSeparator()
        self.toolBar_board.addAction(self.actionBoard_info)
        self.toolBar_graphical.addAction(self.actionSave_image)
        self.toolBar_switch.addAction(self.actionSwitch_ide)

        self.retranslateUi(PinguinoIDE)
        self.tabWidget_files.setCurrentIndex(-1)
        self.tabWidget_tools.setCurrentIndex(1)
        self.tabWidget_browser.setCurrentIndex(1)
        self.tabWidget_blocks_tools.setCurrentIndex(0)
        self.tabWidget_blocks.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(PinguinoIDE)
        PinguinoIDE.setTabOrder(self.tabWidget_files, self.tabWidget_tools)
        PinguinoIDE.setTabOrder(self.tabWidget_tools, self.tabWidget_browser)
        PinguinoIDE.setTabOrder(self.tabWidget_browser, self.comboBox_files)
        PinguinoIDE.setTabOrder(self.comboBox_files, self.listWidget_files)
        PinguinoIDE.setTabOrder(self.listWidget_files, self.tableWidget_variables)
        PinguinoIDE.setTabOrder(self.tableWidget_variables, self.tableWidget_functions)
        PinguinoIDE.setTabOrder(self.tableWidget_functions, self.tableWidget_directives)
        PinguinoIDE.setTabOrder(self.tableWidget_directives, self.lineEdit_search)
        PinguinoIDE.setTabOrder(self.lineEdit_search, self.lineEdit_replace)
        PinguinoIDE.setTabOrder(self.lineEdit_replace, self.checkBox_case_sensitive)
        PinguinoIDE.setTabOrder(self.checkBox_case_sensitive, self.pushButton_search_next)
        PinguinoIDE.setTabOrder(self.pushButton_search_next, self.pushButton_search_previous)
        PinguinoIDE.setTabOrder(self.pushButton_search_previous, self.pushButton_replace)
        PinguinoIDE.setTabOrder(self.pushButton_replace, self.pushButton_replace_all)

    def retranslateUi(self, PinguinoIDE):
        PinguinoIDE.setWindowTitle(QtGui.QApplication.translate("PinguinoIDE", "Pinguino 11", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("PinguinoIDE", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("PinguinoIDE", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("PinguinoIDE", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPinguino.setTitle(QtGui.QApplication.translate("PinguinoIDE", "Pinguino", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("PinguinoIDE", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLinks.setTitle(QtGui.QApplication.translate("PinguinoIDE", "Links", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSource.setTitle(QtGui.QApplication.translate("PinguinoIDE", "Source", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget_tools.setWindowTitle(QtGui.QApplication.translate("PinguinoIDE", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_files.setItemText(0, QtGui.QApplication.translate("PinguinoIDE", "Examples", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_files.setItemText(1, QtGui.QApplication.translate("PinguinoIDE", "Current file dir", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_files.setItemText(2, QtGui.QApplication.translate("PinguinoIDE", "Home", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_files.setItemText(3, QtGui.QApplication.translate("PinguinoIDE", "Other...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_path.setText(QtGui.QApplication.translate("PinguinoIDE", "../", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_tools.setTabText(self.tabWidget_tools.indexOf(self.tab_5), QtGui.QApplication.translate("PinguinoIDE", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_variables.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("PinguinoIDE", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_variables.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("PinguinoIDE", "Line", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_browser.setTabText(self.tabWidget_browser.indexOf(self.tab_7), QtGui.QApplication.translate("PinguinoIDE", "Variables", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_functions.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("PinguinoIDE", "Return", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_functions.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("PinguinoIDE", "Args", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_functions.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("PinguinoIDE", "Line", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_browser.setTabText(self.tabWidget_browser.indexOf(self.tab_6), QtGui.QApplication.translate("PinguinoIDE", "Functions", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_directives.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("PinguinoIDE", "type", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_directives.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("PinguinoIDE", "value", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_directives.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("PinguinoIDE", "Line", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_browser.setTabText(self.tabWidget_browser.indexOf(self.tab_8), QtGui.QApplication.translate("PinguinoIDE", "Directives", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_tools.setTabText(self.tabWidget_tools.indexOf(self.tab_3), QtGui.QApplication.translate("PinguinoIDE", "Source Browser", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("PinguinoIDE", "Replace", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_replace.setText(QtGui.QApplication.translate("PinguinoIDE", "Replace", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_replace_all.setText(QtGui.QApplication.translate("PinguinoIDE", "Replace all", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("PinguinoIDE", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_search_previous.setText(QtGui.QApplication.translate("PinguinoIDE", "Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_search_next.setText(QtGui.QApplication.translate("PinguinoIDE", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_case_sensitive.setText(QtGui.QApplication.translate("PinguinoIDE", "Case sensitive", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_tools.setTabText(self.tabWidget_tools.indexOf(self.tab_4), QtGui.QApplication.translate("PinguinoIDE", "Search Replace", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget_output.setWindowTitle(QtGui.QApplication.translate("PinguinoIDE", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.plainTextEdit_output.setPlainText(QtGui.QApplication.translate("PinguinoIDE", "Welcome to Pinguino 11.0", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_files.setWindowTitle(QtGui.QApplication.translate("PinguinoIDE", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_undo_redo.setWindowTitle(QtGui.QApplication.translate("PinguinoIDE", "Undo Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_edit.setWindowTitle(QtGui.QApplication.translate("PinguinoIDE", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_search_replace.setWindowTitle(QtGui.QApplication.translate("PinguinoIDE", "Search Replace", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_pinguino.setWindowTitle(QtGui.QApplication.translate("PinguinoIDE", "Pinguino", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_board.setWindowTitle(QtGui.QApplication.translate("PinguinoIDE", "Board info", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget_blocks.setWindowTitle(QtGui.QApplication.translate("PinguinoIDE", "Blocks", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_blocks_tools.setTabText(self.tabWidget_blocks_tools.indexOf(self.tab), QtGui.QApplication.translate("PinguinoIDE", "Blocks", None, QtGui.QApplication.UnicodeUTF8))
        self.label_pathg.setText(QtGui.QApplication.translate("PinguinoIDE", "../", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_filesg.setItemText(0, QtGui.QApplication.translate("PinguinoIDE", "Examples", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_filesg.setItemText(1, QtGui.QApplication.translate("PinguinoIDE", "Current file dir", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_filesg.setItemText(2, QtGui.QApplication.translate("PinguinoIDE", "Home", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_filesg.setItemText(3, QtGui.QApplication.translate("PinguinoIDE", "Other...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_blocks_tools.setTabText(self.tabWidget_blocks_tools.indexOf(self.tab_2), QtGui.QApplication.translate("PinguinoIDE", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_graphical.setWindowTitle(QtGui.QApplication.translate("PinguinoIDE", "Graphical mode", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_switch.setWindowTitle(QtGui.QApplication.translate("PinguinoIDE", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_file.setText(QtGui.QApplication.translate("PinguinoIDE", "New file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_file.setShortcut(QtGui.QApplication.translate("PinguinoIDE", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_file.setText(QtGui.QApplication.translate("PinguinoIDE", "Open file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_file.setShortcut(QtGui.QApplication.translate("PinguinoIDE", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_file.setText(QtGui.QApplication.translate("PinguinoIDE", "Save file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_file.setShortcut(QtGui.QApplication.translate("PinguinoIDE", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose_file.setText(QtGui.QApplication.translate("PinguinoIDE", "Close file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose_file.setToolTip(QtGui.QApplication.translate("PinguinoIDE", "Close file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose_file.setShortcut(QtGui.QApplication.translate("PinguinoIDE", "Ctrl+W", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setText(QtGui.QApplication.translate("PinguinoIDE", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setShortcut(QtGui.QApplication.translate("PinguinoIDE", "Ctrl+Z", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setText(QtGui.QApplication.translate("PinguinoIDE", "Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setShortcut(QtGui.QApplication.translate("PinguinoIDE", "Ctrl+Y", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setText(QtGui.QApplication.translate("PinguinoIDE", "Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setShortcut(QtGui.QApplication.translate("PinguinoIDE", "Ctrl+X", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("PinguinoIDE", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setShortcut(QtGui.QApplication.translate("PinguinoIDE", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setText(QtGui.QApplication.translate("PinguinoIDE", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setShortcut(QtGui.QApplication.translate("PinguinoIDE", "Ctrl+V", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear.setText(QtGui.QApplication.translate("PinguinoIDE", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect.setText(QtGui.QApplication.translate("PinguinoIDE", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSearch.setText(QtGui.QApplication.translate("PinguinoIDE", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSearch.setShortcut(QtGui.QApplication.translate("PinguinoIDE", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSearch_and_replace.setText(QtGui.QApplication.translate("PinguinoIDE", "Search and replace", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSearch_and_replace.setShortcut(QtGui.QApplication.translate("PinguinoIDE", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_board.setText(QtGui.QApplication.translate("PinguinoIDE", "Select board", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompile.setText(QtGui.QApplication.translate("PinguinoIDE", "Compile", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompile.setShortcut(QtGui.QApplication.translate("PinguinoIDE", "F5", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpload.setText(QtGui.QApplication.translate("PinguinoIDE", "Upload", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpload.setShortcut(QtGui.QApplication.translate("PinguinoIDE", "F6", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setText(QtGui.QApplication.translate("PinguinoIDE", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setShortcut(QtGui.QApplication.translate("PinguinoIDE", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("PinguinoIDE", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("PinguinoIDE", "About...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionComment_Uncomment_region.setText(QtGui.QApplication.translate("PinguinoIDE", "Comment/Uncomment region", None, QtGui.QApplication.UnicodeUTF8))
        self.actionComment_Uncomment_region.setToolTip(QtGui.QApplication.translate("PinguinoIDE", "Comment/Uncomment region", None, QtGui.QApplication.UnicodeUTF8))
        self.actionComment_Uncomment_region.setShortcut(QtGui.QApplication.translate("PinguinoIDE", "Ctrl+.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionComment_out_region.setText(QtGui.QApplication.translate("PinguinoIDE", "Comment out region", None, QtGui.QApplication.UnicodeUTF8))
        self.actionComment_out_region.setShortcut(QtGui.QApplication.translate("PinguinoIDE", "Ctrl+/", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBoard_info.setText(QtGui.QApplication.translate("PinguinoIDE", "Board info", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStdout.setText(QtGui.QApplication.translate("PinguinoIDE", "Stdout", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStdout.setShortcut(QtGui.QApplication.translate("PinguinoIDE", "F9", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSwitch_ide.setText(QtGui.QApplication.translate("PinguinoIDE", "Switch ide", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSwitch_ide.setShortcut(QtGui.QApplication.translate("PinguinoIDE", "F10", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_image.setText(QtGui.QApplication.translate("PinguinoIDE", "Save image", None, QtGui.QApplication.UnicodeUTF8))
        self.actionView_Pinguino_code.setText(QtGui.QApplication.translate("PinguinoIDE", "View Pinguino code", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_all.setText(QtGui.QApplication.translate("PinguinoIDE", "Save all", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose_all.setText(QtGui.QApplication.translate("PinguinoIDE", "Close all", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWebsite.setText(QtGui.QApplication.translate("PinguinoIDE", "Website", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWiki.setText(QtGui.QApplication.translate("PinguinoIDE", "Wiki", None, QtGui.QApplication.UnicodeUTF8))
        self.actionForum.setText(QtGui.QApplication.translate("PinguinoIDE", "Forum", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBlog.setText(QtGui.QApplication.translate("PinguinoIDE", "Blog", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGroup.setText(QtGui.QApplication.translate("PinguinoIDE", "Group", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShop.setText(QtGui.QApplication.translate("PinguinoIDE", "Shop", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGitHub.setText(QtGui.QApplication.translate("PinguinoIDE", "GitHub", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as.setText(QtGui.QApplication.translate("PinguinoIDE", "Save as", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCurrent_Board.setText(QtGui.QApplication.translate("PinguinoIDE", "Current Board", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCurrent_Board.setShortcut(QtGui.QApplication.translate("PinguinoIDE", "F12", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
